### PR TITLE
closes issue #57

### PR DESCRIPTION
**Pull request by yoasyo25**
Updates cart_spec test for add and subtract item methods and updates substract_course method so that a course with one item in it is deleted from the cart when the user clicks "Decrease Quantity".

### CODE REVIEW

**Comment by samanthagongora** [comment]
Thank you for thinking about that guard clause and pushing this up to development. I think it is one of those fine details that we could have forgotten.

I noticed this includes the search bar. Is the search bar working? @yoasyo25 

closes #77, too.

**Comment by yoasyo25** [comment]
I thought I had deleted all the stuff related to the search bar from this branch. I'm still playing around with the search feature. Figured out how to make it work for one model, categories, but not sure how to do it for courses and categories collectively. Will clean up this branch and submit another pull request. Thanks for noticing this, Sam.

**Review by thedanielvogelsang — CHANGES_REQUESTED** [review]
Hey yohannan, the search bar is still in application.html.erb as of this morning on this pull request. Am I understanding you'd like to remove it before we merge? Or is it in working condition?

**Comment by yoasyo25** [comment]
Hey Daniel and Sam, I have deleted the search form from the nav bar. This branch should be good for merging.

**Comment by DesTodo** [comment]
Appears that there are not conflicts and the search bar is removed. I'm merging this branch into dev. Thanks.

**Pull request merged**
